apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-service
spec:
  selector:
    matchLabels:
      app: leave-service
  template:
    metadata:
      labels:
        app: leave-service
    spec:
      containers:
        - name: leave-service
          image: revtalent-leave-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/revtalent?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: revtalent-secrets
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: revtalent-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: revtalent-secrets
                  key: jwt-secret
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: leave-service
spec:
  ports:
    - port: 8083
  selector:
    app: leave-service