apiVersion: v1
kind: Secret
metadata:
  name: revtalent-secrets
type: Opaque
stringData:
  db-username: revtalentuser
  db-password: revtalent123
  jwt-secret: K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=